import { MANUAL_TOUR, MANUAL_KNOWLEDGE, MANUAL_SOURCE_FILES, TRAINING_TRACKS } from "./conhecimento.js";
const $ = (id) => document.getElementById(id);
const frame=$("systemFrame"), frameStatus=$("frameStatus"), progressBar=$("progressBar"), chapterLabel=$("chapterLabel"), stepCount=$("stepCount"), stepTitle=$("stepTitle"), stepBody=$("stepBody"), stepSource=$("stepSource"), prevBtn=$("prevBtn"), nextBtn=$("nextBtn"), playBtn=$("playBtn"), speedSelect=$("speedSelect"), voiceBtn=$("voiceBtn"), reloadBtn=$("reloadBtn"), roleSelect=$("roleSelect"), trackDialog=$("trackDialog"), trackGrid=$("trackGrid"), mapDialog=$("mapDialog"), mapContent=$("mapContent"), qaForm=$("qaForm"), qaInput=$("qaInput"), qaMessages=$("qaMessages"), quickQuestions=$("quickQuestions"), simCursor=$("simCursor"), balloon=$("targetBalloon"), balloonTitle=$("balloonTitle"), balloonHint=$("balloonHint"), mobileStepCount=$("mobileStepCount");
let activeTrack=null, steps=[], index=0, playing=false, timer=null, voice=false, currentPage="index.html", sourceIndexPromise=null, lastTarget=null, lastContextKey="";
const normalize=(v="")=>String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]+/g," ").replace(/\s+/g," ").trim();
const escapeHtml=(v="")=>String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
function visible(el){if(!el)return false;const r=el.getBoundingClientRect(),s=el.ownerDocument.defaultView.getComputedStyle(el);return r.width>0&&r.height>0&&s.display!=="none"&&s.visibility!=="hidden";}
function findByText(doc,text){const wanted=normalize(text);const candidates=[...doc.querySelectorAll("h1,h2,h3,h4,summary,label,button,a,strong,span,p,small,legend,th,td")].filter(visible);return candidates.find(e=>normalize(e.textContent)===wanted)||candidates.find(e=>normalize(e.textContent).startsWith(wanted))||candidates.find(e=>normalize(e.textContent).includes(wanted));}
function frameDoc(){try{return frame.contentDocument}catch{return null}}
function clearTarget(){const doc=frameDoc();doc?.querySelectorAll('.training-highlight').forEach(e=>e.classList.remove('training-highlight'));balloon.hidden=true;simCursor.classList.remove('active');lastTarget=null;}
function installGuard(doc){if(!doc||doc.__trainingGuard)return;doc.__trainingGuard=true;const guard=e=>{const t=e.target; if(t?.closest?.('a[href^="#/"],summary,[data-open-section]'))return; if(t?.closest?.('button,input,select,textarea,form,label')){e.preventDefault();e.stopImmediatePropagation();frameStatus.textContent='Treinamento seguro: a ação foi demonstrada, mas não executada.';}};doc.addEventListener('click',guard,true);doc.addEventListener('submit',guard,true);doc.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target?.closest?.('button,input,select,textarea,form'))guard(e)},true);}
function roleForStep(step){if(step.id==='login')return {loggedOut:true};return {loggedOut:false,role:activeTrack?.role||roleSelect.value||'dono'};}
function applyContext(step){const ctx=roleForStep(step);if(ctx.role)localStorage.setItem('glamore.training.role',ctx.role);localStorage.setItem('glamore.training.loggedOut',ctx.loggedOut?'true':'false');roleSelect.value=ctx.role||roleSelect.value;}
function pageUrl(step){if(step.page)return `./sistema/${step.page}`;return `./sistema/index.html#/${step.route||'dashboard'}`;}
async function setFrame(step){applyContext(step);const contextKey=`${localStorage.getItem("glamore.training.role")||"dono"}|${localStorage.getItem("glamore.training.loggedOut")||"false"}`;const nextPage=step.page||"index.html";let changed=false;if(contextKey!==lastContextKey){lastContextKey=contextKey;currentPage=nextPage;frame.src=pageUrl(step);changed=true;}else if(currentPage!==nextPage){currentPage=nextPage;frame.src=pageUrl(step);changed=true;}else if(step.page){frame.src=pageUrl(step);changed=true;}else{try{const wanted=`#/${step.route||"dashboard"}`;if(frame.contentWindow.location.hash!==wanted){frame.contentWindow.location.hash=wanted;changed=true;}}catch{frame.src=pageUrl(step);changed=true;}}if(changed){frameStatus.textContent="Abrindo a tela real em modo simulado...";await sleep(700);}return changed;}
async function waitDoc(){for(let i=0;i<35;i++){const d=frameDoc();if(d?.body&&d.readyState!=='loading'){installGuard(d);return d}await sleep(120)}return null;}
async function moveCursor(target){if(!target)return;const fr=frame.getBoundingClientRect(),tr=target.getBoundingClientRect(),stage=$("stageViewport").getBoundingClientRect();const x=fr.left-stage.left+tr.left+Math.min(tr.width*.55,Math.max(18,tr.width-18));const y=fr.top-stage.top+tr.top+Math.min(tr.height*.55,Math.max(18,tr.height-18));simCursor.style.left=`${x}px`;simCursor.style.top=`${y}px`;simCursor.classList.add('active');await sleep(780);simCursor.classList.add('clicking');await sleep(130);simCursor.classList.remove('clicking');}
function placeBalloon(target,step){if(!target||innerWidth<680){balloon.hidden=true;return;}const fr=frame.getBoundingClientRect(),tr=target.getBoundingClientRect(),stage=$("stageViewport").getBoundingClientRect();let left=fr.left-stage.left+tr.right+18,top=fr.top-stage.top+tr.top;if(left+300>stage.width)left=Math.max(14,fr.left-stage.left+tr.left-308);top=Math.max(14,Math.min(top,stage.height-120));balloon.style.left=`${left}px`;balloon.style.top=`${top}px`;balloonTitle.textContent=step.title;balloonHint.textContent='O destaque está sobre a tela real do sistema em modo seguro.';balloon.hidden=false;}
async function highlight(step){const doc=await waitDoc();if(!doc){frameStatus.textContent='Não foi possível carregar a tela demonstrativa.';return false;}clearTarget();let target=null;if(step.target?.selector)target=[...doc.querySelectorAll(step.target.selector)].find(visible)||null;if(!target&&step.target?.text)target=findByText(doc,step.target.text);if(!target)target=doc.querySelector('main.main,#app,body');if(target){target.classList.add('training-highlight');target.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});lastTarget=target;await sleep(300);await moveCursor(target);placeBalloon(target,step);frameStatus.textContent=`Mostrando: ${step.title}`;return true;}return false;}
function current(){return steps[index]||steps[0]}
function speak(step){if(!voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`${step.title}. ${step.body}`);u.lang='pt-BR';u.rate=.98;speechSynthesis.speak(u);}
function saveProgress(){if(!activeTrack)return;localStorage.setItem(`glamore.training.progress.${activeTrack.id}`,String(index));}
async function showStep(next,{auto=false}={}){if(!steps.length)return;index=Math.max(0,Math.min(steps.length-1,Number(next)||0));const step=current();await setFrame(step);chapterLabel.textContent=step.chapter;stepCount.textContent=`${index+1} / ${steps.length}`;mobileStepCount.textContent=stepCount.textContent;stepTitle.textContent=step.title;stepBody.innerHTML=`<p>${escapeHtml(step.body)}</p>`;stepSource.textContent=step.page?`Tela real de treinamento: ${step.page}`:`Tela real de treinamento: #/${step.route||'dashboard'}`;progressBar.style.width=`${((index+1)/steps.length)*100}%`;prevBtn.disabled=index===0;nextBtn.disabled=index===steps.length-1;renderMap();saveProgress();await highlight(step);speak(step);if(playing&&auto)schedule();}
function schedule(){clearTimeout(timer);if(!playing)return;if(index>=steps.length-1){stop();return;}const seconds=Number(current().duration||8)*Number(speedSelect.value||1);timer=setTimeout(()=>showStep(index+1,{auto:true}),seconds*1000)}
function play(){playing=true;playBtn.textContent='Ⅱ Pausar';playBtn.setAttribute('aria-pressed','true');schedule()}
function stop(){playing=false;clearTimeout(timer);playBtn.textContent='▶ Play';playBtn.setAttribute('aria-pressed','false');}
function resolveTrack(track){let list;if(track.steps==='ALL')list=[...MANUAL_TOUR];else if(Array.isArray(track.steps))list=track.steps.map(id=>MANUAL_TOUR.find(s=>s.id===id)).filter(Boolean);else if(track.chapters)list=MANUAL_TOUR.filter(s=>track.chapters.includes(s.chapter));else list=[...MANUAL_TOUR];return list;}
function selectTrack(trackId){activeTrack=TRAINING_TRACKS.find(t=>t.id===trackId)||TRAINING_TRACKS[0];steps=resolveTrack(activeTrack);localStorage.setItem('glamore.training.track',activeTrack.id);roleSelect.value=activeTrack.role||'dono';localStorage.setItem('glamore.training.role',roleSelect.value);localStorage.removeItem('glamore.training.loggedOut');index=Math.min(Number(localStorage.getItem(`glamore.training.progress.${activeTrack.id}`)||0),steps.length-1);trackDialog.close();stop();showStep(index);}
function renderTracks(){trackGrid.innerHTML=TRAINING_TRACKS.map(t=>`<button class="track-card" data-track="${escapeHtml(t.id)}"><span class="icon">${escapeHtml(t.icon)}</span><strong>${escapeHtml(t.title)}</strong><span>${escapeHtml(t.subtitle)}</span></button>`).join('');trackGrid.querySelectorAll('[data-track]').forEach(b=>b.addEventListener('click',()=>selectTrack(b.dataset.track)));}
function renderMap(){if(!steps.length)return;mapContent.innerHTML=steps.map((s,i)=>`<button class="map-step ${i===index?'active':''}" data-step="${i}"><small>${escapeHtml(s.chapter)} · ${i+1}</small><strong>${escapeHtml(s.title)}</strong></button>`).join('');mapContent.querySelectorAll('[data-step]').forEach(b=>b.addEventListener('click',()=>{mapDialog.close();stop();showStep(Number(b.dataset.step))}));}
function tokens(text){return new Set(normalize(text).split(' ').filter(w=>w.length>2))}
function scoreKnowledge(q,item){const qt=tokens(q),title=normalize(item.title),keys=(item.keywords||[]).map(normalize),answer=normalize(item.answer);let score=0;for(const word of qt){if(title.includes(word))score+=5;if(keys.some(k=>k.includes(word)))score+=4;if(answer.includes(word))score+=1;}const nq=normalize(q);if(keys.some(k=>nq.includes(k)||k.includes(nq)))score+=10;return score;}
async function sourceIndex(){if(sourceIndexPromise)return sourceIndexPromise;sourceIndexPromise=(async()=>{const rows=[];for(const file of MANUAL_SOURCE_FILES){try{const r=await fetch(`./fontes/${file}`);if(!r.ok)continue;const text=await r.text();const clean=text.replace(/data:image\/[a-z]+;base64,[A-Za-z0-9+/=]+/g,'[imagem omitida]');const lines=clean.split(/\r?\n/);for(let i=0;i<lines.length;i+=18){const chunk=lines.slice(i,i+24).join('\n').trim();if(chunk.length>80)rows.push({file,line:i+1,text:chunk,norm:normalize(chunk)});}}catch{}}return rows;})();return sourceIndexPromise;}
function addMessage(cls,html){const div=document.createElement('div');div.className=cls;div.innerHTML=html;qaMessages.appendChild(div);qaMessages.scrollTop=qaMessages.scrollHeight;}
async function answerQuestion(question){addMessage('qa-user',escapeHtml(question));const ranked=MANUAL_KNOWLEDGE.map(i=>({i,score:scoreKnowledge(question,i)})).sort((a,b)=>b.score-a.score);const best=ranked[0];if(best&&best.score>=5){const item=best.i;addMessage('qa-answer',`<h3>${escapeHtml(item.title)}</h3><div>${escapeHtml(item.answer)}</div><div class="answer-sources"><strong>Fontes:</strong> ${(item.sources||[]).map(escapeHtml).join(' · ')}</div><button data-answer-step="${escapeHtml(item.step||'')}">Mostrar na tela real</button>`);qaMessages.querySelectorAll('[data-answer-step]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.answerStep;const pos=steps.findIndex(s=>s.id===id);if(pos>=0)showStep(pos);else{const source=MANUAL_TOUR.find(s=>s.id===id);if(source){steps=[source];index=0;showStep(0)}}});return;}const idx=await sourceIndex(),qt=[...tokens(question)];const matches=idx.map(row=>({row,score:qt.reduce((n,w)=>n+(row.norm.includes(w)?1:0),0)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3);if(matches.length){addMessage('qa-answer',`<h3>Evidências próximas encontradas</h3><div>Não existe uma resposta curada suficiente para afirmar isso com segurança. Encontrei estes trechos relacionados:</div><div class="answer-sources">${matches.map(m=>`${escapeHtml(m.row.file)}:${m.row.line} — ${escapeHtml(m.row.text.slice(0,260))}`).join('<br><br>')}</div>`);}else addMessage('qa-answer','<h3>Não há evidência segura</h3><div>Não encontrei no código, documentos e testes uma base suficiente para responder essa pergunta sem suposição. Reformule usando o nome da tela, botão, coleção ou operação.</div>');}
function quick(){const qs=['Como funciona a venda com falta?','Quantidade e peso são independentes?','Por que produção aprovada não cria ordem?','Como funciona o estorno de inventário?','Quem pode ver a Auditoria?','Como a produção pronta atende uma venda?'];quickQuestions.innerHTML=qs.map(q=>`<button>${escapeHtml(q)}</button>`).join('');quickQuestions.querySelectorAll('button').forEach(b=>b.onclick=()=>{qaInput.value=b.textContent;answerQuestion(b.textContent)});}
prevBtn.onclick=()=>{stop();showStep(index-1)};nextBtn.onclick=()=>{stop();showStep(index+1)};playBtn.onclick=()=>playing?stop():play();$("restartBtn").onclick=()=>{stop();showStep(0)};voiceBtn.onclick=()=>{voice=!voice;voiceBtn.textContent=voice?'Narração ligada':'Narração desligada';voiceBtn.setAttribute('aria-pressed',String(voice));if(!voice)speechSynthesis?.cancel?.();else speak(current())};reloadBtn.onclick=()=>{frame.src=pageUrl(current());setTimeout(()=>highlight(current()),800)};roleSelect.onchange=()=>{localStorage.setItem('glamore.training.role',roleSelect.value);localStorage.removeItem('glamore.training.loggedOut');frame.src=pageUrl(current());setTimeout(()=>highlight(current()),850)};$("chooseTrackBtn").onclick=()=>trackDialog.showModal();$("mapBtn").onclick=()=>{renderMap();mapDialog.showModal()};document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());qaForm.onsubmit=e=>{e.preventDefault();const q=qaInput.value.trim();if(q){qaInput.value='';answerQuestion(q)}};$("clearQaBtn").onclick=()=>qaMessages.innerHTML='<div class="qa-system">Conversa limpa. Faça uma nova pergunta.</div>';frame.addEventListener('load',()=>{const doc=frameDoc();installGuard(doc);setTimeout(()=>highlight(current()),250)});document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)){stop();showStep(index+1)}if(e.key==='ArrowLeft'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)){stop();showStep(index-1)}if(e.key==='Escape'){trackDialog.open&&trackDialog.close();mapDialog.open&&mapDialog.close();}});
renderTracks();quick();const saved=localStorage.getItem('glamore.training.track')||'rapido';selectTrack(saved);setTimeout(()=>{if(!localStorage.getItem('glamore.training.welcomed')){localStorage.setItem('glamore.training.welcomed','1');trackDialog.showModal()}},500);
