export const DEMO_USERS = {
  "demo-owner": {
    "uid": "demo-owner",
    "nome": "Vitor Gomes",
    "email": "treinamento.dono@glamore.demo",
    "papel": "dono",
    "cargo": "Administrador Master",
    "ativo": true,
    "criadoEm": "2026-07-01T10:00:00.000Z"
  },
  "demo-manager": {
    "uid": "demo-manager",
    "nome": "Marina Souza",
    "email": "treinamento.gerente@glamore.demo",
    "papel": "gerente",
    "cargo": "Gerente",
    "ativo": true,
    "criadoEm": "2026-07-01T10:00:00.000Z"
  },
  "demo-seller": {
    "uid": "demo-seller",
    "nome": "Daniela Lima",
    "email": "treinamento.vendas@glamore.demo",
    "papel": "vendedor",
    "cargo": "Vendedora",
    "ativo": true,
    "criadoEm": "2026-07-01T10:00:00.000Z"
  },
  "demo-attendant": {
    "uid": "demo-attendant",
    "nome": "Lucas Alves",
    "email": "treinamento.atendimento@glamore.demo",
    "papel": "atendente",
    "cargo": "Atendente",
    "ativo": true,
    "criadoEm": "2026-07-01T10:00:00.000Z"
  },
  "demo-delivery": {
    "uid": "demo-delivery",
    "nome": "Rafael Santos",
    "email": "treinamento.entrega@glamore.demo",
    "papel": "entregador",
    "cargo": "Entregador",
    "ativo": true,
    "criadoEm": "2026-07-01T10:00:00.000Z"
  }
};

export const DEMO_DATA = {
  "clientes": {
    "cli-capital": {
      "nome": "CAPITAL JOALHERIA LTDA",
      "documento": "17.855.301/0001-08",
      "telefone": "(11) 99999-1111",
      "email": "compras@capital.demo",
      "responsavel": "Carla Martins",
      "endereco": "Rua das Joias, 100",
      "cidade": "São Paulo",
      "uf": "SP",
      "tipo": "Joalheria",
      "ativo": true,
      "criadoEm": "2026-07-01T10:00:00.000Z"
    },
    "cli-glamore": {
      "nome": "GLAMORE GOMES IND. E COM. LTDA",
      "documento": "11.340.235/0001-49",
      "telefone": "(17) 3231-5909",
      "email": "contato@glamore.demo",
      "responsavel": "Vitor Gomes",
      "endereco": "Rua Barão de Cotegipe, 205",
      "cidade": "São José do Rio Preto",
      "uf": "SP",
      "tipo": "Fábrica",
      "ativo": true,
      "criadoEm": "2026-07-01T10:00:00.000Z"
    },
    "cli-lumiere": {
      "nome": "LUMIÈRE JOIAS",
      "documento": "32.410.550/0001-10",
      "telefone": "(16) 98888-2200",
      "email": "pedidos@lumiere.demo",
      "responsavel": "Paula Rocha",
      "endereco": "Av. Central, 450",
      "cidade": "Ribeirão Preto",
      "uf": "SP",
      "tipo": "Joalheria",
      "ativo": true,
      "criadoEm": "2026-07-03T10:00:00.000Z"
    }
  },
  "produtos": {
    "2740AGL_15_OURO_18K": {
      "codigo": "2740AGL",
      "codigoOriginal": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "tipo": "Anel",
      "material": "Ouro 18K",
      "medida": "15",
      "pesoMedio": 0.78,
      "pesoMedioContabil": 0.78,
      "estoqueDisponivel": 3,
      "estoqueVendido": 2,
      "estoqueReservado": 0,
      "estoqueConsignado": 0,
      "estoqueMinimo": 3,
      "estoqueCritico": 3,
      "estoqueIdeal": 8,
      "estoqueSugestao": 5,
      "pesoEntradaAcumulado": 3.9,
      "pesoSaidaAcumulado": 1.56,
      "pesoTotalDisponivel": 2.34,
      "ultimaMovimentacaoEm": "2026-07-16T14:20:00.000Z",
      "fotoUrl": ""
    },
    "2740AGL_17_OURO_18K": {
      "codigo": "2740AGL",
      "codigoOriginal": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "tipo": "Anel",
      "material": "Ouro 18K",
      "medida": "17",
      "pesoMedio": 0.82,
      "pesoMedioContabil": 0.82,
      "estoqueDisponivel": 10,
      "estoqueVendido": 10,
      "estoqueReservado": 0,
      "estoqueConsignado": 0,
      "estoqueMinimo": 4,
      "estoqueCritico": 3,
      "estoqueIdeal": 15,
      "estoqueSugestao": 5,
      "pesoEntradaAcumulado": 16.4,
      "pesoSaidaAcumulado": 8.2,
      "pesoTotalDisponivel": 8.2,
      "ultimaMovimentacaoEm": "2026-07-16T15:10:00.000Z",
      "fotoUrl": ""
    },
    "ALM0027F_18_OURO_18K": {
      "codigo": "ALM0027F",
      "codigoOriginal": "ALM0027F",
      "descricao": "ALIANÇA FEMININA 18K / MOISSANITE",
      "tipo": "Aliança",
      "material": "Ouro 18K",
      "medida": "18",
      "pesoMedio": 2.16,
      "pesoMedioContabil": 2.16,
      "estoqueDisponivel": 2,
      "estoqueVendido": 1,
      "estoqueReservado": 0,
      "estoqueConsignado": 1,
      "estoqueMinimo": 3,
      "estoqueCritico": 2,
      "estoqueIdeal": 8,
      "estoqueSugestao": 6,
      "pesoEntradaAcumulado": 8.64,
      "pesoSaidaAcumulado": 2.16,
      "pesoConsignadoAcumulado": 2.16,
      "pesoTotalDisponivel": 4.32,
      "ultimaMovimentacaoEm": "2026-07-15T09:25:00.000Z",
      "fotoUrl": ""
    },
    "BR500_0_OURO_18K": {
      "codigo": "BR500",
      "codigoOriginal": "BR500",
      "descricao": "BRINCO PONTO DE LUZ",
      "tipo": "Brinco",
      "material": "Ouro 18K",
      "medida": "Único",
      "pesoMedio": 1.25,
      "pesoMedioContabil": 1.25,
      "estoqueDisponivel": 0,
      "estoqueVendido": 4,
      "estoqueReservado": 0,
      "estoqueConsignado": 0,
      "estoqueMinimo": 2,
      "estoqueCritico": 1,
      "estoqueIdeal": 5,
      "estoqueSugestao": 5,
      "pesoEntradaAcumulado": 5,
      "pesoSaidaAcumulado": 5,
      "pesoTotalDisponivel": 0,
      "ultimaMovimentacaoEm": "2026-07-14T11:00:00.000Z",
      "fotoUrl": ""
    },
    "COR100_45_PRATA_925": {
      "codigo": "COR100",
      "codigoOriginal": "COR100",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "tipo": "Corrente",
      "material": "Prata 925",
      "medida": "45 cm",
      "pesoMedio": 3.4,
      "pesoMedioContabil": 3.4,
      "estoqueDisponivel": 5,
      "estoqueVendido": 0,
      "estoqueReservado": 1,
      "estoqueConsignado": 0,
      "estoqueMinimo": 2,
      "estoqueCritico": 2,
      "estoqueIdeal": 7,
      "estoqueSugestao": 2,
      "pesoEntradaAcumulado": 20.4,
      "pesoReservadoAcumulado": 3.4,
      "pesoTotalDisponivel": 17,
      "ultimaMovimentacaoEm": "2026-07-12T16:40:00.000Z",
      "fotoUrl": ""
    },
    "PEND200_UNICO_OURO_10K": {
      "codigo": "PEND200",
      "codigoOriginal": "PEND200",
      "descricao": "PINGENTE CORAÇÃO OURO 10K",
      "tipo": "Pingente",
      "material": "Ouro 10K",
      "medida": "Único",
      "pesoMedio": 0.95,
      "pesoMedioContabil": 0.95,
      "estoqueDisponivel": 1,
      "estoqueVendido": 0,
      "estoqueReservado": 0,
      "estoqueConsignado": 0,
      "estoqueMinimo": 2,
      "estoqueCritico": 1,
      "estoqueIdeal": 5,
      "estoqueSugestao": 4,
      "pesoEntradaAcumulado": 0.95,
      "pesoSaidaAcumulado": 0,
      "pesoTotalDisponivel": 0.95,
      "ultimaMovimentacaoEm": "2026-07-10T08:10:00.000Z",
      "fotoUrl": ""
    }
  },
  "pedidos": {
    "pedido-26762": {
      "numeroPedido": "26762",
      "pedidoPdfNumero": "26762",
      "arquivoNome": "venda-26762.pdf",
      "dataPedido": "2026-07-03",
      "tipoImportacao": "venda_inteligente",
      "clienteId": "cli-glamore",
      "clienteNome": "GLAMORE GOMES IND. E COM. LTDA",
      "vendedor": "DANIELA",
      "status": "finalizada",
      "importacaoStatus": "concluida",
      "quantidadeSolicitadaTotal": 10,
      "quantidadeBaixadaTotal": 10,
      "quantidadeFaltanteTotal": 0,
      "qtdItens": 1,
      "qtdPecas": 10,
      "criadoEm": "2026-07-15T16:08:20.000Z",
      "atualizadoEm": "2026-07-15T16:08:32.000Z"
    },
    "pedido-26783": {
      "numeroPedido": "26783",
      "pedidoPdfNumero": "26783",
      "arquivoNome": "venda-26783.pdf",
      "dataPedido": "2026-07-07",
      "tipoImportacao": "venda_inteligente",
      "clienteId": "cli-glamore",
      "clienteNome": "GLAMORE GOMES IND. E COM. LTDA",
      "vendedor": "DANIELA",
      "status": "finalizada",
      "importacaoStatus": "concluida",
      "quantidadeSolicitadaTotal": 2,
      "quantidadeBaixadaTotal": 2,
      "quantidadeFaltanteTotal": 0,
      "qtdItens": 1,
      "qtdPecas": 2,
      "criadoEm": "2026-07-15T18:57:35.000Z",
      "atualizadoEm": "2026-07-15T18:57:37.000Z"
    },
    "pedido-26810": {
      "numeroPedido": "26810",
      "pedidoPdfNumero": "26810",
      "arquivoNome": "venda-falta-26810.pdf",
      "dataPedido": "2026-07-16",
      "tipoImportacao": "venda_inteligente",
      "clienteId": "cli-capital",
      "clienteNome": "CAPITAL JOALHERIA LTDA",
      "vendedor": "DANIELA",
      "status": "pendente_producao",
      "importacaoStatus": "concluida",
      "quantidadeSolicitadaTotal": 8,
      "quantidadeBaixadaTotal": 5,
      "quantidadeFaltanteTotal": 3,
      "quantidadePendenteProducao": 3,
      "qtdItens": 1,
      "qtdPecas": 8,
      "criadoEm": "2026-07-16T13:15:00.000Z",
      "atualizadoEm": "2026-07-16T13:16:00.000Z"
    },
    "pedido-26800-est": {
      "numeroPedido": "26800",
      "pedidoPdfNumero": "26800",
      "arquivoNome": "venda-estornada-26800.pdf",
      "dataPedido": "2026-07-12",
      "tipoImportacao": "venda_inteligente",
      "clienteId": "cli-lumiere",
      "clienteNome": "LUMIÈRE JOIAS",
      "vendedor": "DANIELA",
      "status": "estornado",
      "importacaoStatus": "estornada",
      "estornoReconciliado": true,
      "qtdItens": 1,
      "qtdPecas": 1,
      "criadoEm": "2026-07-12T11:00:00.000Z",
      "estornadoEm": "2026-07-13T10:20:00.000Z"
    }
  },
  "vendas": {
    "sale-26762": {
      "pedidoId": "pedido-26762",
      "origemDocumentoId": "pedido-26762",
      "pedidoPdfNumero": "26762",
      "numeroPedido": "26762",
      "codigo": "2740AGL",
      "produtoId": "2740AGL_17_OURO_18K",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "cliente": "GLAMORE GOMES IND. E COM. LTDA",
      "clienteNome": "GLAMORE GOMES IND. E COM. LTDA",
      "vendedor": "DANIELA",
      "quantidadeSolicitada": 10,
      "quantidadeBaixada": 10,
      "quantidadePendenteAnaliseGestor": 0,
      "quantidadePendenteProducao": 0,
      "pesoTotalSolicitado": 8.2,
      "pesoTotalBaixado": 8.2,
      "status": "finalizada",
      "criadoEm": "2026-07-15T16:08:31.000Z",
      "finalizadaEm": "2026-07-15T16:08:31.000Z"
    },
    "sale-26783": {
      "pedidoId": "pedido-26783",
      "origemDocumentoId": "pedido-26783",
      "pedidoPdfNumero": "26783",
      "numeroPedido": "26783",
      "codigo": "2740AGL",
      "produtoId": "2740AGL_15_OURO_18K",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "15",
      "cliente": "GLAMORE GOMES IND. E COM. LTDA",
      "clienteNome": "GLAMORE GOMES IND. E COM. LTDA",
      "vendedor": "DANIELA",
      "quantidadeSolicitada": 2,
      "quantidadeBaixada": 2,
      "quantidadePendenteAnaliseGestor": 0,
      "quantidadePendenteProducao": 0,
      "pesoTotalSolicitado": 1.56,
      "pesoTotalBaixado": 1.56,
      "status": "finalizada",
      "criadoEm": "2026-07-15T18:57:36.000Z",
      "finalizadaEm": "2026-07-15T18:57:36.000Z"
    },
    "sale-26810": {
      "pedidoId": "pedido-26810",
      "origemDocumentoId": "pedido-26810",
      "pedidoPdfNumero": "26810",
      "numeroPedido": "26810",
      "codigo": "COR100",
      "produtoId": "COR100_45_PRATA_925",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "material": "Prata 925",
      "medida": "45 cm",
      "cliente": "CAPITAL JOALHERIA LTDA",
      "clienteNome": "CAPITAL JOALHERIA LTDA",
      "vendedor": "DANIELA",
      "quantidadeSolicitada": 8,
      "quantidadeBaixada": 5,
      "quantidadePendenteAnaliseGestor": 0,
      "quantidadePendenteProducao": 3,
      "pesoTotalSolicitado": 27.2,
      "pesoTotalBaixado": 17,
      "status": "pendente_producao",
      "criadoEm": "2026-07-16T13:15:30.000Z"
    },
    "sale-26800": {
      "pedidoId": "pedido-26800-est",
      "origemDocumentoId": "pedido-26800-est",
      "pedidoPdfNumero": "26800",
      "numeroPedido": "26800",
      "codigo": "PEND200",
      "produtoId": "PEND200_UNICO_OURO_10K",
      "descricao": "PINGENTE CORAÇÃO OURO 10K",
      "material": "Ouro 10K",
      "medida": "Único",
      "cliente": "LUMIÈRE JOIAS",
      "clienteNome": "LUMIÈRE JOIAS",
      "vendedor": "DANIELA",
      "quantidadeSolicitada": 1,
      "quantidadeBaixada": 1,
      "pesoTotalSolicitado": 0.95,
      "pesoTotalBaixado": 0.95,
      "status": "estornada",
      "estornadoEm": "2026-07-13T10:20:00.000Z",
      "estornoMotivo": "Cliente cancelou antes da entrega.",
      "criadoEm": "2026-07-12T11:00:00.000Z"
    }
  },
  "consignacoes": {
    "consig-001": {
      "cliente": "LUMIÈRE JOIAS",
      "clienteNome": "LUMIÈRE JOIAS",
      "produtoId": "ALM0027F_18_OURO_18K",
      "codigo": "ALM0027F",
      "descricao": "ALIANÇA FEMININA 18K / MOISSANITE",
      "material": "Ouro 18K",
      "medida": "18",
      "quantidade": 1,
      "peso": 2.16,
      "status": "pendente",
      "vendedor": "DANIELA",
      "criadoEm": "2026-07-15T09:25:00.000Z"
    }
  },
  "cadastrosMostruario": {
    "cat-1": {
      "codigo": "PEND200",
      "descricao": "PINGENTE CORAÇÃO OURO 10K",
      "material": "Ouro 10K",
      "medida": "Único",
      "tipo": "Pingente",
      "criadoEm": "2026-07-05T10:00:00.000Z"
    }
  },
  "inventariosEstoque": {
    "inv-26764": {
      "numeroPedido": "26764",
      "pedidoPdfNumero": "26764",
      "arquivoNome": "inventario-26764.pdf",
      "tipoImportacao": "estoque_atual",
      "tipoRegistro": "inventario_estoque_pdf",
      "status": "concluido",
      "importacaoStatus": "concluida",
      "qtdItens": 2,
      "qtdPecas": 9,
      "itens": [
        {
          "codigo": "2740AGL",
          "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
          "material": "Ouro 18K",
          "medida": "15",
          "quantidade": 5,
          "pesoTotalLinha": 3.9,
          "lote": "LOTE-AGL15-0712"
        },
        {
          "codigo": "ALM0027F",
          "descricao": "ALIANÇA FEMININA 18K / MOISSANITE",
          "material": "Ouro 18K",
          "medida": "18",
          "quantidade": 4,
          "pesoTotalLinha": 8.64,
          "lote": "LOTE-ALM18"
        }
      ],
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "criadoPor": "Marina Souza"
    },
    "inv-26760-est": {
      "numeroPedido": "26760",
      "pedidoPdfNumero": "26760",
      "arquivoNome": "inventario-antigo-26760.pdf",
      "tipoImportacao": "estoque_atual",
      "tipoRegistro": "inventario_estoque_pdf",
      "status": "estornado",
      "importacaoStatus": "estornada",
      "qtdItens": 1,
      "qtdPecas": 4,
      "estornoQuantidadeEsperada": 4,
      "estornoPecasRemovidasTotal": 4,
      "estornoPesoDocumento": 5,
      "estornoMotivo": "Inventário lançado em duplicidade.",
      "estornadoEm": "2026-07-11T17:30:00.000Z",
      "criadoEm": "2026-07-10T08:00:00.000Z"
    }
  },
  "pedidosProducao": {
    "pp-001": {
      "numeroPedido": "PP-001",
      "produtoId": "BR500_0_OURO_18K",
      "codigo": "BR500",
      "descricao": "BRINCO PONTO DE LUZ",
      "material": "Ouro 18K",
      "medida": "Único",
      "quantidade": 5,
      "quantidadeProduzida": 0,
      "status": "pendente",
      "prioridade": "alta",
      "criadoEm": "2026-07-16T08:00:00.000Z"
    }
  },
  "producoes": {
    "prod-pdf-001": {
      "id": "prod-pdf-001",
      "numeroPedido": "26790",
      "pedidoPdfNumero": "26790",
      "arquivoNome": "producao-pronta-26790.pdf",
      "tipoImportacao": "producao_pronta",
      "tipoRegistro": "cabecalho_producao_pronta_pdf",
      "status": "concluida",
      "importacaoStatus": "concluida",
      "quantidadeRecebidaTotal": 20,
      "quantidadeBaixadaVendas": 10,
      "quantidadeExcedenteEstoque": 10,
      "pesoBaixadoVendas": 8.2,
      "qtdItens": 1,
      "qtdPecas": 20,
      "itens": [
        {
          "codigo": "2740AGL",
          "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
          "material": "Ouro 18K",
          "medida": "17",
          "quantidade": 20,
          "pesoTotalLinha": 16.4,
          "lote": "LOTE-PROD-AGL17"
        }
      ],
      "criadoEm": "2026-07-16T15:00:00.000Z",
      "criadoPor": "Marina Souza"
    },
    "prod-manual-pend": {
      "id": "prod-manual-pend",
      "tipoRegistro": "entrada_producao_manual",
      "produtoId": "PEND200_UNICO_OURO_10K",
      "codigo": "PEND200",
      "descricao": "PINGENTE CORAÇÃO OURO 10K",
      "material": "Ouro 10K",
      "medida": "Único",
      "quantidade": 1,
      "pesoTotal": 0.95,
      "pesoUnitario": 0.95,
      "lote": "LOTE-PEND",
      "responsavel": "Marina Souza",
      "status": "pronta",
      "criadoEm": "2026-07-10T08:10:00.000Z"
    }
  },
  "lotes": {
    "LOTE-AGL15-0712": {
      "lote": "LOTE-AGL15-0712",
      "produtoId": "2740AGL_15_OURO_18K",
      "quantidadeEntrada": 5,
      "quantidadeDisponivel": 3,
      "pesoEntrada": 3.9,
      "status": "ativo",
      "origem": "inventario",
      "pedidoId": "inv-26764",
      "criadoEm": "2026-07-12T09:00:00.000Z"
    },
    "LOTE-PROD-AGL17": {
      "lote": "LOTE-PROD-AGL17",
      "produtoId": "2740AGL_17_OURO_18K",
      "quantidadeEntrada": 20,
      "quantidadeDisponivel": 10,
      "pesoEntrada": 16.4,
      "status": "ativo",
      "origem": "producao_pronta",
      "pedidoId": "prod-pdf-001",
      "criadoEm": "2026-07-16T15:00:00.000Z"
    },
    "LOTE-ALM18": {
      "lote": "LOTE-ALM18",
      "produtoId": "ALM0027F_18_OURO_18K",
      "quantidadeEntrada": 4,
      "quantidadeDisponivel": 2,
      "pesoEntrada": 8.64,
      "status": "ativo",
      "origem": "inventario",
      "pedidoId": "inv-26764",
      "criadoEm": "2026-07-12T09:00:00.000Z"
    },
    "LOTE-COR45": {
      "lote": "LOTE-COR45",
      "produtoId": "COR100_45_PRATA_925",
      "quantidadeEntrada": 6,
      "quantidadeDisponivel": 5,
      "pesoEntrada": 20.4,
      "status": "ativo",
      "origem": "inventario",
      "pedidoId": "inv-26766",
      "criadoEm": "2026-07-12T16:40:00.000Z"
    },
    "LOTE-PEND": {
      "lote": "LOTE-PEND",
      "produtoId": "PEND200_UNICO_OURO_10K",
      "quantidadeEntrada": 1,
      "quantidadeDisponivel": 1,
      "pesoEntrada": 0.95,
      "status": "ativo",
      "origem": "producao_manual",
      "pedidoId": "prod-manual-pend",
      "criadoEm": "2026-07-10T08:10:00.000Z"
    }
  },
  "pecasEstoque": {
    "agl15-01": {
      "pecaCodigo": "AGL15-01",
      "produtoId": "2740AGL_15_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "15",
      "loteId": "LOTE-AGL15-0712",
      "lote": "LOTE-AGL15-0712",
      "status": "disponivel",
      "pesoReal": 0.78,
      "pesoBase": 0.78,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26764",
      "inventarioId": "inv-26764",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl15-02": {
      "pecaCodigo": "AGL15-02",
      "produtoId": "2740AGL_15_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "15",
      "loteId": "LOTE-AGL15-0712",
      "lote": "LOTE-AGL15-0712",
      "status": "disponivel",
      "pesoReal": 0.78,
      "pesoBase": 0.78,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26764",
      "inventarioId": "inv-26764",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl15-03": {
      "pecaCodigo": "AGL15-03",
      "produtoId": "2740AGL_15_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "15",
      "loteId": "LOTE-AGL15-0712",
      "lote": "LOTE-AGL15-0712",
      "status": "disponivel",
      "pesoReal": 0.78,
      "pesoBase": 0.78,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26764",
      "inventarioId": "inv-26764",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl15-04": {
      "pecaCodigo": "AGL15-04",
      "produtoId": "2740AGL_15_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "15",
      "loteId": "LOTE-AGL15-0712",
      "lote": "LOTE-AGL15-0712",
      "status": "vendido",
      "pesoReal": 0.78,
      "pesoBase": 0.78,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26764",
      "inventarioId": "inv-26764",
      "producaoId": "",
      "vendaId": "sale-26783",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl15-05": {
      "pecaCodigo": "AGL15-05",
      "produtoId": "2740AGL_15_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "15",
      "loteId": "LOTE-AGL15-0712",
      "lote": "LOTE-AGL15-0712",
      "status": "vendido",
      "pesoReal": 0.78,
      "pesoBase": 0.78,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26764",
      "inventarioId": "inv-26764",
      "producaoId": "",
      "vendaId": "sale-26783",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-01": {
      "pecaCodigo": "AGL17-01",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-02": {
      "pecaCodigo": "AGL17-02",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-03": {
      "pecaCodigo": "AGL17-03",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-04": {
      "pecaCodigo": "AGL17-04",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-05": {
      "pecaCodigo": "AGL17-05",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-06": {
      "pecaCodigo": "AGL17-06",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-07": {
      "pecaCodigo": "AGL17-07",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-08": {
      "pecaCodigo": "AGL17-08",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-09": {
      "pecaCodigo": "AGL17-09",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-10": {
      "pecaCodigo": "AGL17-10",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "disponivel",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-11": {
      "pecaCodigo": "AGL17-11",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-12": {
      "pecaCodigo": "AGL17-12",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-13": {
      "pecaCodigo": "AGL17-13",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-14": {
      "pecaCodigo": "AGL17-14",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-15": {
      "pecaCodigo": "AGL17-15",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-16": {
      "pecaCodigo": "AGL17-16",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-17": {
      "pecaCodigo": "AGL17-17",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-18": {
      "pecaCodigo": "AGL17-18",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-19": {
      "pecaCodigo": "AGL17-19",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "agl17-20": {
      "pecaCodigo": "AGL17-20",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "loteId": "LOTE-PROD-AGL17",
      "lote": "LOTE-PROD-AGL17",
      "status": "vendido",
      "pesoReal": 0.82,
      "pesoBase": 0.82,
      "origem": "entrada_producao_pdf",
      "pedidoId": "prod-pdf-001",
      "inventarioId": "",
      "producaoId": "prod-pdf-001",
      "vendaId": "sale-26762",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "alm18-01": {
      "pecaCodigo": "ALM18-01",
      "produtoId": "ALM0027F_18_OURO_18K",
      "codigo": "ALM0027F",
      "descricao": "ALIANÇA FEMININA 18K / MOISSANITE",
      "material": "Ouro 18K",
      "medida": "18",
      "loteId": "LOTE-ALM18",
      "lote": "LOTE-ALM18",
      "status": "disponivel",
      "pesoReal": 2.16,
      "pesoBase": 2.16,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26765",
      "inventarioId": "inv-26765",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "alm18-02": {
      "pecaCodigo": "ALM18-02",
      "produtoId": "ALM0027F_18_OURO_18K",
      "codigo": "ALM0027F",
      "descricao": "ALIANÇA FEMININA 18K / MOISSANITE",
      "material": "Ouro 18K",
      "medida": "18",
      "loteId": "LOTE-ALM18",
      "lote": "LOTE-ALM18",
      "status": "disponivel",
      "pesoReal": 2.16,
      "pesoBase": 2.16,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26765",
      "inventarioId": "inv-26765",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "alm18-03": {
      "pecaCodigo": "ALM18-03",
      "produtoId": "ALM0027F_18_OURO_18K",
      "codigo": "ALM0027F",
      "descricao": "ALIANÇA FEMININA 18K / MOISSANITE",
      "material": "Ouro 18K",
      "medida": "18",
      "loteId": "LOTE-ALM18",
      "lote": "LOTE-ALM18",
      "status": "vendido",
      "pesoReal": 2.16,
      "pesoBase": 2.16,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26765",
      "inventarioId": "inv-26765",
      "producaoId": "",
      "vendaId": "sale-alm",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "alm18-04": {
      "pecaCodigo": "ALM18-04",
      "produtoId": "ALM0027F_18_OURO_18K",
      "codigo": "ALM0027F",
      "descricao": "ALIANÇA FEMININA 18K / MOISSANITE",
      "material": "Ouro 18K",
      "medida": "18",
      "loteId": "LOTE-ALM18",
      "lote": "LOTE-ALM18",
      "status": "consignado",
      "pesoReal": 2.16,
      "pesoBase": 2.16,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26765",
      "inventarioId": "inv-26765",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "consig-001",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "br500-01": {
      "pecaCodigo": "BR500-01",
      "produtoId": "BR500_0_OURO_18K",
      "codigo": "BR500",
      "descricao": "BRINCO PONTO DE LUZ",
      "material": "Ouro 18K",
      "medida": "Único",
      "loteId": "LOTE-BR500",
      "lote": "LOTE-BR500",
      "status": "vendido",
      "pesoReal": 1.25,
      "pesoBase": 1.25,
      "origem": "entrada_producao_manual",
      "pedidoId": "prod-manual-br",
      "inventarioId": "",
      "producaoId": "prod-manual-br",
      "vendaId": "sale-br",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "br500-02": {
      "pecaCodigo": "BR500-02",
      "produtoId": "BR500_0_OURO_18K",
      "codigo": "BR500",
      "descricao": "BRINCO PONTO DE LUZ",
      "material": "Ouro 18K",
      "medida": "Único",
      "loteId": "LOTE-BR500",
      "lote": "LOTE-BR500",
      "status": "vendido",
      "pesoReal": 1.25,
      "pesoBase": 1.25,
      "origem": "entrada_producao_manual",
      "pedidoId": "prod-manual-br",
      "inventarioId": "",
      "producaoId": "prod-manual-br",
      "vendaId": "sale-br",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "br500-03": {
      "pecaCodigo": "BR500-03",
      "produtoId": "BR500_0_OURO_18K",
      "codigo": "BR500",
      "descricao": "BRINCO PONTO DE LUZ",
      "material": "Ouro 18K",
      "medida": "Único",
      "loteId": "LOTE-BR500",
      "lote": "LOTE-BR500",
      "status": "vendido",
      "pesoReal": 1.25,
      "pesoBase": 1.25,
      "origem": "entrada_producao_manual",
      "pedidoId": "prod-manual-br",
      "inventarioId": "",
      "producaoId": "prod-manual-br",
      "vendaId": "sale-br",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "br500-04": {
      "pecaCodigo": "BR500-04",
      "produtoId": "BR500_0_OURO_18K",
      "codigo": "BR500",
      "descricao": "BRINCO PONTO DE LUZ",
      "material": "Ouro 18K",
      "medida": "Único",
      "loteId": "LOTE-BR500",
      "lote": "LOTE-BR500",
      "status": "vendido",
      "pesoReal": 1.25,
      "pesoBase": 1.25,
      "origem": "entrada_producao_manual",
      "pedidoId": "prod-manual-br",
      "inventarioId": "",
      "producaoId": "prod-manual-br",
      "vendaId": "sale-br",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "cor45-01": {
      "pecaCodigo": "COR45-01",
      "produtoId": "COR100_45_PRATA_925",
      "codigo": "COR100",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "material": "Prata 925",
      "medida": "45 cm",
      "loteId": "LOTE-COR45",
      "lote": "LOTE-COR45",
      "status": "disponivel",
      "pesoReal": 3.4,
      "pesoBase": 3.4,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26766",
      "inventarioId": "inv-26766",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "cor45-02": {
      "pecaCodigo": "COR45-02",
      "produtoId": "COR100_45_PRATA_925",
      "codigo": "COR100",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "material": "Prata 925",
      "medida": "45 cm",
      "loteId": "LOTE-COR45",
      "lote": "LOTE-COR45",
      "status": "disponivel",
      "pesoReal": 3.4,
      "pesoBase": 3.4,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26766",
      "inventarioId": "inv-26766",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "cor45-03": {
      "pecaCodigo": "COR45-03",
      "produtoId": "COR100_45_PRATA_925",
      "codigo": "COR100",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "material": "Prata 925",
      "medida": "45 cm",
      "loteId": "LOTE-COR45",
      "lote": "LOTE-COR45",
      "status": "disponivel",
      "pesoReal": 3.4,
      "pesoBase": 3.4,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26766",
      "inventarioId": "inv-26766",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "cor45-04": {
      "pecaCodigo": "COR45-04",
      "produtoId": "COR100_45_PRATA_925",
      "codigo": "COR100",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "material": "Prata 925",
      "medida": "45 cm",
      "loteId": "LOTE-COR45",
      "lote": "LOTE-COR45",
      "status": "disponivel",
      "pesoReal": 3.4,
      "pesoBase": 3.4,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26766",
      "inventarioId": "inv-26766",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "cor45-05": {
      "pecaCodigo": "COR45-05",
      "produtoId": "COR100_45_PRATA_925",
      "codigo": "COR100",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "material": "Prata 925",
      "medida": "45 cm",
      "loteId": "LOTE-COR45",
      "lote": "LOTE-COR45",
      "status": "disponivel",
      "pesoReal": 3.4,
      "pesoBase": 3.4,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26766",
      "inventarioId": "inv-26766",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "cor45-06": {
      "pecaCodigo": "COR45-06",
      "produtoId": "COR100_45_PRATA_925",
      "codigo": "COR100",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "material": "Prata 925",
      "medida": "45 cm",
      "loteId": "LOTE-COR45",
      "lote": "LOTE-COR45",
      "status": "reservado",
      "pesoReal": 3.4,
      "pesoBase": 3.4,
      "origem": "entrada_inventario_pdf",
      "pedidoId": "inv-26766",
      "inventarioId": "inv-26766",
      "producaoId": "",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "reserva-001",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    },
    "pend-01": {
      "pecaCodigo": "PEND-01",
      "produtoId": "PEND200_UNICO_OURO_10K",
      "codigo": "PEND200",
      "descricao": "PINGENTE CORAÇÃO OURO 10K",
      "material": "Ouro 10K",
      "medida": "Único",
      "loteId": "LOTE-PEND",
      "lote": "LOTE-PEND",
      "status": "disponivel",
      "pesoReal": 0.95,
      "pesoBase": 0.95,
      "origem": "entrada_producao_manual",
      "pedidoId": "prod-manual-pend",
      "inventarioId": "",
      "producaoId": "prod-manual-pend",
      "vendaId": "",
      "consignacaoId": "",
      "reservaId": "",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "atualizadoEm": "2026-07-16T15:10:00.000Z"
    }
  },
  "movimentos": {
    "mov-1": {
      "tipo": "entrada_inventario",
      "produtoId": "2740AGL_15_OURO_18K",
      "quantidade": 5,
      "peso": 3.9,
      "pedidoId": "inv-26764",
      "origem": "pdf",
      "observacao": "Entrada por inventário 26764.",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "criadoPor": "Marina Souza",
      "criadoPorUid": "demo-manager",
      "usuarioPapelLabel": "Gerente"
    },
    "mov-2": {
      "tipo": "baixa_venda_inteligente",
      "produtoId": "2740AGL_15_OURO_18K",
      "quantidade": 2,
      "peso": 1.56,
      "pedidoId": "pedido-26783",
      "origem": "pdf",
      "observacao": "Baixa real por peça física.",
      "criadoEm": "2026-07-15T18:57:36.000Z",
      "criadoPor": "Daniela Lima",
      "criadoPorUid": "demo-seller",
      "usuarioPapelLabel": "Vendedora"
    },
    "mov-3": {
      "tipo": "entrada_producao",
      "produtoId": "2740AGL_17_OURO_18K",
      "quantidade": 20,
      "peso": 16.4,
      "pedidoId": "prod-pdf-001",
      "origem": "producao",
      "observacao": "Produção pronta recebida.",
      "criadoEm": "2026-07-16T15:00:00.000Z",
      "criadoPor": "Marina Souza",
      "criadoPorUid": "demo-manager",
      "usuarioPapelLabel": "Gerente"
    },
    "mov-4": {
      "tipo": "baixa_venda_inteligente",
      "produtoId": "2740AGL_17_OURO_18K",
      "quantidade": 10,
      "peso": 8.2,
      "pedidoId": "pedido-26762",
      "origem": "pdf",
      "observacao": "Atendimento da venda com produção aprovada.",
      "criadoEm": "2026-07-16T15:10:00.000Z",
      "criadoPor": "Marina Souza",
      "criadoPorUid": "demo-manager",
      "usuarioPapelLabel": "Gerente"
    },
    "mov-5": {
      "tipo": "saida_consignacao",
      "produtoId": "ALM0027F_18_OURO_18K",
      "quantidade": 1,
      "peso": 2.16,
      "pedidoId": "consig-001",
      "origem": "manual",
      "observacao": "Peça enviada em consignação.",
      "criadoEm": "2026-07-15T09:25:00.000Z",
      "criadoPor": "Daniela Lima",
      "criadoPorUid": "demo-seller",
      "usuarioPapelLabel": "Vendedora"
    },
    "mov-6": {
      "tipo": "reserva",
      "produtoId": "COR100_45_PRATA_925",
      "quantidade": 1,
      "peso": 3.4,
      "pedidoId": "reserva-001",
      "origem": "manual",
      "observacao": "Reserva para cliente.",
      "criadoEm": "2026-07-16T13:00:00.000Z",
      "criadoPor": "Lucas Alves",
      "criadoPorUid": "demo-attendant",
      "usuarioPapelLabel": "Atendente"
    }
  },
  "estoqueMovimentos": {
    "mov-1": {
      "tipo": "entrada_inventario",
      "produtoId": "2740AGL_15_OURO_18K",
      "quantidade": 5,
      "peso": 3.9,
      "pedidoId": "inv-26764",
      "origem": "pdf",
      "observacao": "Entrada por inventário 26764.",
      "criadoEm": "2026-07-12T09:00:00.000Z",
      "criadoPor": "Marina Souza",
      "criadoPorUid": "demo-manager",
      "usuarioPapelLabel": "Gerente"
    },
    "mov-2": {
      "tipo": "baixa_venda_inteligente",
      "produtoId": "2740AGL_15_OURO_18K",
      "quantidade": 2,
      "peso": 1.56,
      "pedidoId": "pedido-26783",
      "origem": "pdf",
      "observacao": "Baixa real por peça física.",
      "criadoEm": "2026-07-15T18:57:36.000Z",
      "criadoPor": "Daniela Lima",
      "criadoPorUid": "demo-seller",
      "usuarioPapelLabel": "Vendedora"
    },
    "mov-3": {
      "tipo": "entrada_producao",
      "produtoId": "2740AGL_17_OURO_18K",
      "quantidade": 20,
      "peso": 16.4,
      "pedidoId": "prod-pdf-001",
      "origem": "producao",
      "observacao": "Produção pronta recebida.",
      "criadoEm": "2026-07-16T15:00:00.000Z",
      "criadoPor": "Marina Souza",
      "criadoPorUid": "demo-manager",
      "usuarioPapelLabel": "Gerente"
    },
    "mov-4": {
      "tipo": "baixa_venda_inteligente",
      "produtoId": "2740AGL_17_OURO_18K",
      "quantidade": 10,
      "peso": 8.2,
      "pedidoId": "pedido-26762",
      "origem": "pdf",
      "observacao": "Atendimento da venda com produção aprovada.",
      "criadoEm": "2026-07-16T15:10:00.000Z",
      "criadoPor": "Marina Souza",
      "criadoPorUid": "demo-manager",
      "usuarioPapelLabel": "Gerente"
    },
    "mov-5": {
      "tipo": "saida_consignacao",
      "produtoId": "ALM0027F_18_OURO_18K",
      "quantidade": 1,
      "peso": 2.16,
      "pedidoId": "consig-001",
      "origem": "manual",
      "observacao": "Peça enviada em consignação.",
      "criadoEm": "2026-07-15T09:25:00.000Z",
      "criadoPor": "Daniela Lima",
      "criadoPorUid": "demo-seller",
      "usuarioPapelLabel": "Vendedora"
    },
    "mov-6": {
      "tipo": "reserva",
      "produtoId": "COR100_45_PRATA_925",
      "quantidade": 1,
      "peso": 3.4,
      "pedidoId": "reserva-001",
      "origem": "manual",
      "observacao": "Reserva para cliente.",
      "criadoEm": "2026-07-16T13:00:00.000Z",
      "criadoPor": "Lucas Alves",
      "criadoPorUid": "demo-attendant",
      "usuarioPapelLabel": "Atendente"
    }
  },
  "alertasOperacionais": {
    "alert-26810": {
      "tipo": "venda_sem_estoque",
      "tipoRegistro": "alerta_gestor_venda_sem_estoque",
      "status": "pendente",
      "prioridade": "urgente",
      "numeroPedido": "26810",
      "pedidoPdfNumero": "26810",
      "origemDocumentoId": "pedido-26810",
      "vendaId": "sale-26810",
      "produtoId": "COR100_45_PRATA_925",
      "codigo": "COR100",
      "descricao": "CORRENTE VENEZIANA PRATA 925",
      "material": "Prata 925",
      "medida": "45 cm",
      "cliente": "CAPITAL JOALHERIA LTDA",
      "quantidadeSolicitada": 8,
      "quantidadeBaixada": 5,
      "quantidadeFaltante": 3,
      "quantidadePendenteAnalise": 3,
      "pesoTotalReferencia": 27.2,
      "mensagem": "Pedido 26810: faltam 3 peças de COR100 45 cm. Gestor deve analisar reposição/produção.",
      "decisaoEsperada": "produzir, comprar, ajustar estoque ou cancelar",
      "criadoEm": "2026-07-16T13:15:45.000Z",
      "criadoPor": "Daniela Lima",
      "criadoPorUid": "demo-seller"
    },
    "alert-26790-res": {
      "tipo": "venda_sem_estoque",
      "tipoRegistro": "alerta_gestor_venda_sem_estoque",
      "status": "resolvido",
      "prioridade": "normal",
      "numeroPedido": "26790",
      "pedidoPdfNumero": "26790",
      "produtoId": "2740AGL_17_OURO_18K",
      "codigo": "2740AGL",
      "descricao": "AN. SOLITÁRIO 18K / ZIRCÔNIA 3MM",
      "material": "Ouro 18K",
      "medida": "17",
      "cliente": "LUMIÈRE JOIAS",
      "quantidadeSolicitada": 10,
      "quantidadeBaixada": 0,
      "quantidadeFaltante": 10,
      "quantidadeProducaoAprovada": 20,
      "quantidadeProducaoRecebida": 20,
      "quantidadeAplicadaVenda": 10,
      "quantidadeExcedenteEstoque": 10,
      "decisaoGestor": "produzir",
      "resolvidoEm": "2026-07-16T15:10:00.000Z",
      "criadoEm": "2026-07-15T11:00:00.000Z"
    }
  },
  "vendedores": {
    "vend-daniela": {
      "nome": "DANIELA",
      "email": "daniela@glamore.demo",
      "cargo": "Vendedora",
      "percentualComissao": 3,
      "ativo": true
    },
    "vend-joao": {
      "nome": "JOÃO",
      "email": "joao@glamore.demo",
      "cargo": "Vendedor",
      "percentualComissao": 2.5,
      "ativo": true
    }
  },
  "tiposProduto": {
    "alianca": {
      "nome": "Aliança",
      "ativo": true
    },
    "anel": {
      "nome": "Anel",
      "ativo": true
    },
    "brinco": {
      "nome": "Brinco",
      "ativo": true
    },
    "corrente": {
      "nome": "Corrente",
      "ativo": true
    },
    "pingente": {
      "nome": "Pingente",
      "ativo": true
    },
    "pulseira": {
      "nome": "Pulseira",
      "ativo": true
    },
    "personalizado": {
      "nome": "Personalizado",
      "ativo": true
    }
  },
  "parametrosTecnicos": {
    "ouro18": {
      "material": "Ouro 18K",
      "teor": "750",
      "perdaPercentual": 8,
      "observacao": "Parâmetro demonstrativo; validar com a fábrica."
    },
    "prata": {
      "material": "Prata 925",
      "teor": "925",
      "perdaPercentual": 5,
      "observacao": "Parâmetro demonstrativo; validar com a fábrica."
    }
  },
  "configuracoes": {
    "percentualComissaoPadrao": 3,
    "diasEstoqueParado": 90,
    "estoqueMinimoPadrao": 3
  },
  "usuarios": {
    "demo-owner": {
      "uid": "demo-owner",
      "nome": "Vitor Gomes",
      "email": "treinamento.dono@glamore.demo",
      "papel": "dono",
      "cargo": "Administrador Master",
      "ativo": true,
      "criadoEm": "2026-07-01T10:00:00.000Z"
    },
    "demo-manager": {
      "uid": "demo-manager",
      "nome": "Marina Souza",
      "email": "treinamento.gerente@glamore.demo",
      "papel": "gerente",
      "cargo": "Gerente",
      "ativo": true,
      "criadoEm": "2026-07-01T10:00:00.000Z"
    },
    "demo-seller": {
      "uid": "demo-seller",
      "nome": "Daniela Lima",
      "email": "treinamento.vendas@glamore.demo",
      "papel": "vendedor",
      "cargo": "Vendedora",
      "ativo": true,
      "criadoEm": "2026-07-01T10:00:00.000Z"
    },
    "demo-attendant": {
      "uid": "demo-attendant",
      "nome": "Lucas Alves",
      "email": "treinamento.atendimento@glamore.demo",
      "papel": "atendente",
      "cargo": "Atendente",
      "ativo": true,
      "criadoEm": "2026-07-01T10:00:00.000Z"
    },
    "demo-delivery": {
      "uid": "demo-delivery",
      "nome": "Rafael Santos",
      "email": "treinamento.entrega@glamore.demo",
      "papel": "entregador",
      "cargo": "Entregador",
      "ativo": true,
      "criadoEm": "2026-07-01T10:00:00.000Z"
    }
  },
  "auditoria": {
    "audit-01": {
      "acao": "importacao_confirmada",
      "colecao": "inventariosEstoque",
      "documentoId": "inv-26764",
      "motivo": "Importação operacional de inventário por PDF",
      "resumo": "Inventário 26764 · 9 peças · 12,540 g",
      "statusAuditoria": "concluida",
      "criadoEm": "2026-07-12T09:00:02.000Z",
      "dataHora": "12/07/2026, 09:00:02",
      "usuarioUid": "demo-manager",
      "usuarioEmail": "treinamento.gerente@glamore.demo",
      "usuarioNome": "Marina Souza",
      "usuarioPapel": "gerente",
      "usuarioPapelLabel": "Gerente"
    },
    "audit-02": {
      "acao": "pedido_venda_inteligente_agrupado_importado",
      "colecao": "vendas",
      "documentoId": "sale-26783",
      "motivo": "Importação inteligente com baixa por SKU operacional",
      "resumo": "2740AGL · Nº 15 · pedido 2 · baixado 2 · alerta gestor 0",
      "statusAuditoria": "concluida",
      "criadoEm": "2026-07-15T18:57:36.000Z",
      "dataHora": "15/07/2026, 18:57:36",
      "usuarioUid": "demo-seller",
      "usuarioEmail": "treinamento.vendas@glamore.demo",
      "usuarioNome": "Daniela Lima",
      "usuarioPapel": "vendedor",
      "usuarioPapelLabel": "Vendedora"
    },
    "audit-03": {
      "acao": "alerta_gestor_venda_sem_estoque",
      "colecao": "alertasOperacionais",
      "documentoId": "alert-26810",
      "motivo": "Venda inteligente com falta de estoque para análise do gestor",
      "resumo": "Pedido 26810 · faltam 3 peças de COR100",
      "statusAuditoria": "concluida",
      "criadoEm": "2026-07-16T13:15:45.000Z",
      "dataHora": "16/07/2026, 13:15:45",
      "usuarioUid": "demo-seller",
      "usuarioEmail": "treinamento.vendas@glamore.demo",
      "usuarioNome": "Daniela Lima",
      "usuarioPapel": "vendedor",
      "usuarioPapelLabel": "Vendedora"
    },
    "audit-04": {
      "acao": "producao_aprovada_em_alerta",
      "colecao": "alertasOperacionais",
      "documentoId": "alert-26790-res",
      "motivo": "Gestor aprovou produzir 20 peças",
      "resumo": "Produção aprovada pelo alerta: 20 peças. A aprovação não criou ordem automática.",
      "statusAuditoria": "concluida",
      "criadoEm": "2026-07-16T14:40:00.000Z",
      "dataHora": "16/07/2026, 14:40:00",
      "usuarioUid": "demo-manager",
      "usuarioEmail": "treinamento.gerente@glamore.demo",
      "usuarioNome": "Marina Souza",
      "usuarioPapel": "gerente",
      "usuarioPapelLabel": "Gerente"
    },
    "audit-05": {
      "acao": "producao_pronta_aplicada_alerta_venda",
      "colecao": "producoes",
      "documentoId": "prod-pdf-001",
      "motivo": "Produção pronta aplicada à venda pendente",
      "resumo": "20 recebidas · 10 baixadas na venda · 10 excedentes no estoque",
      "statusAuditoria": "concluida",
      "criadoEm": "2026-07-16T15:10:00.000Z",
      "dataHora": "16/07/2026, 15:10:00",
      "usuarioUid": "demo-manager",
      "usuarioEmail": "treinamento.gerente@glamore.demo",
      "usuarioNome": "Marina Souza",
      "usuarioPapel": "gerente",
      "usuarioPapelLabel": "Gerente"
    },
    "audit-06": {
      "acao": "venda_estornada",
      "colecao": "vendas",
      "documentoId": "sale-26800",
      "motivo": "Cliente cancelou antes da entrega.",
      "justificativaObrigatoria": true,
      "resumo": "Estorno concluído de 1 venda. 1 peça e 0,950 g devolvidos ao estoque.",
      "statusAuditoria": "concluida",
      "criadoEm": "2026-07-13T10:20:00.000Z",
      "dataHora": "13/07/2026, 10:20:00",
      "usuarioUid": "demo-owner",
      "usuarioEmail": "treinamento.dono@glamore.demo",
      "usuarioNome": "Vitor Gomes",
      "usuarioPapel": "dono",
      "usuarioPapelLabel": "Administrador Master"
    },
    "audit-07": {
      "acao": "inventario_pdf_estornado",
      "colecao": "inventariosEstoque",
      "documentoId": "inv-26760-est",
      "motivo": "Inventário lançado em duplicidade.",
      "justificativaObrigatoria": true,
      "resumo": "Inventário estornado: 4/4 peças e 5,000 g removidos.",
      "statusAuditoria": "concluida",
      "criadoEm": "2026-07-11T17:30:00.000Z",
      "dataHora": "11/07/2026, 17:30:00",
      "usuarioUid": "demo-owner",
      "usuarioEmail": "treinamento.dono@glamore.demo",
      "usuarioNome": "Vitor Gomes",
      "usuarioPapel": "dono",
      "usuarioPapelLabel": "Administrador Master"
    },
    "audit-08": {
      "acao": "regras_operacao_alteradas",
      "colecao": "configuracoes",
      "documentoId": "geral",
      "motivo": "Alteração das regras da operação",
      "resumo": "Estoque parado 90 dias · mínimo padrão 3 · comissão padrão 3%",
      "statusAuditoria": "concluida",
      "criadoEm": "2026-07-10T09:00:00.000Z",
      "dataHora": "10/07/2026, 09:00:00",
      "usuarioUid": "demo-owner",
      "usuarioEmail": "treinamento.dono@glamore.demo",
      "usuarioNome": "Vitor Gomes",
      "usuarioPapel": "dono",
      "usuarioPapelLabel": "Administrador Master"
    }
  },
  "iaConsultas": {
    "ia-1": {
      "pergunta": "O que precisa produzir?",
      "titulo": "Produção sugerida",
      "resumo": "BR500 e itens com alerta pendente.",
      "criadoEm": "2026-07-16T16:00:00.000Z",
      "usuarioEmail": "treinamento.gerente@glamore.demo"
    }
  },
  "comissoes": {
    "com-1": {
      "vendaId": "sale-26762",
      "vendedor": "DANIELA",
      "baseCalculo": 0,
      "percentual": 3,
      "valor": 0,
      "status": "pendente",
      "criadoEm": "2026-07-15T10:00:00.000Z"
    }
  }
};
